# Site settings
title: 실전코딩 기술 블로그
description: 실무에서 배운 개발 노하우와 기술적 인사이트를 공유합니다
url: "https://realcoding.blog"
baseurl: ""

# Author information
author:
  name: Kevin Park
  email: kevinpark@okyc.kr
  github: realcoding2003
  linkedin: realcoding

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kevin Park"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Timezone
timezone: Asia/Seoul

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Social media
github_username: realcoding2003
linkedin_username: realcoding

# Google Analytics
google_analytics: G-W3MR94BSXV

# Google AdSense
google_adsense: ca-pub-9012129960393497

# Comments (utterances 사용)
comments:
  provider: utterances
  utterances:
    repo: realcoding2003/realcoding2003.github.io
    issue_term: pathname
    theme: github-light
